name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # ou a versão que você está usando

    - name: Install dependencies
      run: npm install  # Garantir que todas as dependências, incluindo devDependencies, sejam instaladas

    - name: Run tests
      run: npm test  # Comando para rodar os testes
