name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'   # Altere para uma versão LTS como 16, 18 ou 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
