name: CI 

# Configuração de gatilhos para executar o workflow
on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  CI:
    # Define o sistema operacional
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Do NodeJS
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: 21.5.0

      - name: Instalação do mocha e dos pacotes para teste
        run: |
          cd src;
          npm install -g mocha;
          npm install 
